[phases.setup]
nixPkgs = [
    "php83",
    "php83Extensions.pdo_mysql",
    "php83Extensions.mbstring",
    "php83Extensions.tokenizer",
    "php83Extensions.xml",
    "php83Extensions.ctype",
    "php83Extensions.curl",
    "php83Extensions.fileinfo",
    "php83Extensions.gd",
    "php83Extensions.openssl",
    "php83Extensions.zip",
    "php83Extensions.bcmath",
    "nodejs_20",
    "npm"
]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm install",
    "npm run build"
]
